// lib/modules/ui/localization.dart

import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  static const _defaultLocale = 'en';
  static const _supportedLocales = {'en', 'vi', 'zh'};

  String _locale = _defaultLocale;
  Future<void>? _loadOperation;

  String get locale => _locale;

  LanguageProvider();

  /// In-memory locale for tests; never reads or writes user preferences.
  @visibleForTesting
  LanguageProvider.forTesting(String locale)
    : assert(_supportedLocales.contains(locale)),
      _locale = locale;

  /// Loads the persisted locale before the widget tree is built.
  ///
  /// The JSON store is the primary source because it works in portable
  /// Windows builds even when the SharedPreferences Windows plugin is not
  /// available. SharedPreferences remains a compatibility fallback for
  /// existing installations.
  Future<void> load() => _loadOperation ??= _loadLocale();

  List<File> _configCandidates() {
    final candidates = <File>[];
    final exeConfig = File(
      p.join(p.dirname(Platform.resolvedExecutable), 'config.json'),
    );
    final cwdConfig = File(p.join(Directory.current.path, 'config.json'));
    candidates.add(exeConfig);
    if (p.normalize(cwdConfig.path) != p.normalize(exeConfig.path)) {
      candidates.add(cwdConfig);
    }

    final appData = Platform.environment['APPDATA'];
    if (appData != null && appData.trim().isNotEmpty) {
      final appDataConfig = File(p.join(appData, 'JA ADB Tool', 'config.json'));
      if (!candidates.any(
        (file) => p.normalize(file.path) == p.normalize(appDataConfig.path),
      )) {
        candidates.add(appDataConfig);
      }
    }
    return candidates;
  }

  File _fallbackLocaleFile() {
    final appData = Platform.environment['APPDATA'];
    if (appData != null && appData.trim().isNotEmpty) {
      return File(p.join(appData, 'JA ADB Tool', 'locale.json'));
    }
    return File(
      p.join(p.dirname(Platform.resolvedExecutable), '.ja_adb_tool_locale'),
    );
  }

  String? _readLocaleFromFile(File file) {
    if (!file.existsSync()) return null;
    try {
      final decoded = jsonDecode(file.readAsStringSync());
      if (decoded is Map) {
        final value = decoded['locale']?.toString();
        if (_supportedLocales.contains(value)) return value;
      }
    } catch (_) {
      // Try the next persistence source without preventing app startup.
    }
    return null;
  }

  String? _readConfigLocale() {
    for (final file in _configCandidates()) {
      final locale = _readLocaleFromFile(file);
      if (locale != null) return locale;
    }
    return _readLocaleFromFile(_fallbackLocaleFile());
  }

  Future<String?> _readSharedPreferencesLocale() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final value = prefs.getString('app_locale');
      return _supportedLocales.contains(value) ? value : null;
    } catch (_) {
      return null;
    }
  }

  Future<void> _loadLocale() async {
    final persisted =
        _readConfigLocale() ?? await _readSharedPreferencesLocale();
    if (persisted != null && persisted != _locale) {
      _locale = persisted;
      notifyListeners();
    }
  }

  void _writeLocaleToFile(File file, String value) {
    Map<String, dynamic> data = <String, dynamic>{};
    if (file.existsSync()) {
      final content = file.readAsStringSync();
      if (content.trim().isNotEmpty) {
        final decoded = jsonDecode(content);
        if (decoded is Map) {
          data = Map<String, dynamic>.from(decoded);
        }
      }
    }
    data['locale'] = value;
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert(data),
      flush: true,
    );
  }

  Future<void> _persistLocale(String value) async {
    final candidates = _configCandidates();
    final existing = candidates.where((file) => file.existsSync()).toList();
    final targets = existing.isNotEmpty ? existing : [candidates.first];
    var saved = false;
    for (final file in targets) {
      try {
        _writeLocaleToFile(file, value);
        saved = true;
        break;
      } catch (_) {
        // A read-only install directory can fall through to AppData.
      }
    }

    if (!saved) {
      try {
        _writeLocaleToFile(_fallbackLocaleFile(), value);
      } catch (_) {
        // Keep the in-memory locale even if every persistence location fails.
      }
    }
  }

  Future<void> setLocale(String value) async {
    if (!_supportedLocales.contains(value)) return;
    if (value == _locale) return;
    _locale = value;
    notifyListeners();
    await _persistLocale(value);
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('app_locale', value);
    } catch (_) {
      // JSON persistence above is the reliable Windows/portable path.
    }
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'sync_history_summary': 'Direction: {direction} | Mirror: {mirror}',
      'yes_label': 'Yes',
      'no_label': 'No',
      'sync_status_label': 'Status: {status}',
      'sync_starting': 'Starting...',
      'sync_scanning': 'Scanning...',
      'sync_comparing': 'Comparing...',
      'sync_running': 'Syncing...',
      'sync_completed': 'Completed',
      'sync_error': 'Error',
      'sync_cancelled': 'Cancelled',
      'sync_paused': 'Paused',
      'parent_directory': 'Go to parent directory',
      'delete_selected_success': 'Deleted selected items successfully!',
      'delete_some_failed': 'Failed to delete some items.',
      'create_directory_failed': 'Failed to create directory',
      'delete_item_failed': 'Failed to delete item.',
      'retry_action': 'Retry',
      'refresh_action': 'Refresh',
      'rescan_media': 'Rescan Media',
      'media_scan_hint':
          'Scan the device media index to view photos and videos.',
      'split_apks_label': 'Split APKs',
      'xapk_archive': 'XAPK Bundle Archive',
      'standalone_apk': 'Standalone APK',
      'target_device_ready': 'Target Device Ready',
      'android_device_label': 'Android Device',
      'sideload_hint': 'Select APK or XAPK files above to start sideloading.',
      'copied_package_id': 'Copied Package ID',
      'version_label': 'Version',
      'type_label': 'Type',
      'terminal_log': 'Terminal Log',
      'log_copied': 'Log copied to clipboard',
      'installer_waiting': 'Ready. Waiting for installation to start...',
      'copy_package_id': 'Copy Package ID',
      'system_app_badge': 'SYSTEM APP',
      'user_app_badge': 'USER APP',
      'frozen_badge': 'FROZEN',
      'active_badge': 'ACTIVE',
      'processing_label': 'Processing...',
      'sync_preview_failed': 'Unable to create sync preview.',
      'sync_preview_title': 'Sync preview',
      'files_to_delete': 'Files to delete',
      'confirm_delete_hint': 'Type DELETE to confirm',
      'browse_pc_folder': 'Browse PC Folder',
      'restore_configuration': 'Restore configuration',
      'two_way_newest': 'Two-Way (Newest)',
      'select_pc_directory': 'Select PC Directory',
      'delta_sync_title': 'Bidirectional Delta Sync',
      'delta_sync_hint':
          'Only new or modified files based on file size and timestamp are transferred, keeping transfer cycles lightning fast.',
      'dry_run_title': 'Pre-flight Dry Run Verification',
      'dry_run_hint':
          'A full scan preview is calculated before touching files. You will see exactly how many files will be added or modified.',
      'mirror_mode_title': 'Mirror Mode (Delete Extra)',
      'console_log': 'Console Log',
      'sync_waiting': 'Waiting for sync to start...',
      'items_count': '{count} items',
      'no_files_matching': 'No files matching "{query}"',
      'error_details': 'Error: {error}',
      'media_downloaded': 'Successfully downloaded {count} files to {path}',
      'media_partial_download':
          'Copy completed with warnings. Checked folder: {path}',
      'media_folder_set': 'Media download folder set to: {path}',
      'create_target_failed': 'Failed to create target directory: {error}',
      'packages_prepared':
          '{count} package(s) prepared for sequential installation.',
      'copied_value': 'Copied: {value}',
      'installed_time': 'Installed: {time}',
      'freeze_app_failed': 'Failed to freeze {app}',
      'unfreeze_app_failed': 'Failed to unfreeze {app}',
      'extracting_app': 'Extracting {app}...',
      'extracting_apps': 'Extracting {count} apps...',
      'sync_scanned': 'Scanned {pc} PC files and {android} Android files.',
      'sync_copy_count': '{count} copy/update',
      'sync_delete_count': '{count} delete',
      'sync_more_files': '… and {count} more file(s)',
      'app_title': 'JA ADB Tool',
      'no_device_connected': 'No Device Connected',
      'select_device': 'Select an Android device from the sidebar to begin.',
      'adb_setup_title': 'Enable USB Debugging',
      'adb_setup_subtitle': 'Connect your Android phone in a few steps',
      'adb_image_disclaimer':
          'Illustrations use a generic Android layout; labels may vary by phone brand.',
      'adb_illustration_phone': 'Android',
      'adb_illustration_debug': 'USB Debug',
      'adb_image_zoom': 'Click to enlarge',
      'adb_step_1': 'Open Settings on your phone.',
      'adb_step_2':
          'Open About phone, then tap Build number seven times to unlock Developer options.',
      'adb_step_3': 'Open Developer options and turn on USB debugging.',
      'adb_step_4':
          'Connect the phone by USB, unlock it, and allow the RSA prompt.',
      'adb_setup_note':
          'Keep the phone unlocked while connecting. Then refresh the device list.',
      'adb_refresh_button': 'Refresh devices',
      'refresh_devices': 'Refresh Device List',
      'scrcpy_tab': 'Screen Mirror',
      'file_explorer_tab': 'File Explorer',
      'latest_media_tab': 'Latest Media',
      'installer_tab': 'App Installer',
      'settings_tab': 'Advanced Settings',
      'advanced_settings': 'Advanced Settings',
      'launch_mirror': 'Launch Mirroring',
      'launch_standalone_mirror': 'Launch Standalone Mirror',
      'stop_mirror': 'Stop Mirroring',
      'take_screenshot': 'Take Screenshot',
      'select_screenshot_folder': 'Select screenshot folder',
      'select_download_folder': 'Select media download folder',
      'predefined_label': 'Predefined:',
      'select_predefined_hint': 'Select a template...',
      'scrcpy_options': 'Mirroring Options',
      'scrcpy_profiles': 'Scrcpy Profiles',
      'scrcpy_profile_hint': 'Profile name',
      'save_profile': 'Save Profile',
      'delete_profile': 'Delete Profile',
      'profile_saved': 'Scrcpy profile saved.',
      'profile_delete_confirm': 'Delete profile "{name}"?',
      'stay_on_top': 'Always on Top',
      'fullscreen': 'Fullscreen',
      'no_control': 'Read-Only (No Control)',
      'keep_awake': 'Keep Device Awake',
      'borderless': 'Borderless Window',
      'disable_audio': 'Disable Audio (No Audio)',
      'mirror_quality_preset': 'Quality Preset',
      'mirror_preset_low': 'Low / Wi-Fi',
      'mirror_preset_balanced': 'Balanced',
      'mirror_preset_high': 'High / USB',
      'mirror_preset_low_desc': '1024px • 30fps • 3Mbps (Lowest latency)',
      'mirror_preset_balanced_desc': '1600px • 60fps • 6Mbps (Recommended)',
      'mirror_preset_high_desc': '1920px • 60fps • 10Mbps (Crisp USB)',
      'mirror_starting': 'Connecting...',
      'mirror_stopping': 'Stopping...',
      'mirror_initializing_hint':
          'Initializing Scrcpy & syncing video stream...',
      'mirror_error_title': 'Screen Mirror Launch Failed',
      'mirror_open_standalone': 'Open in Separate Window',
      'mirror_diagnostics': 'Mirror Diagnostics',
      'pc_side': 'Computer (PC)',
      'android_side': 'Android Device',
      'download_selected': 'Download to PC',
      'upload_files': 'Upload to Android',
      'new_folder': 'New Folder',
      'delete_selected': 'Delete',
      'loading': 'Loading...',
      'status': 'Status',
      'path_to_adb': 'Path to adb.exe',
      'path_to_scrcpy': 'Path to scrcpy.exe',
      'path_settings_title': 'Tool Paths',
      'path_settings_subtitle':
          'Expand only when changing ADB, Scrcpy, or Gnirehtet',
      'select_apk_xapk': 'Select APK or XAPK file',
      'drag_drop_apk_xapk': 'Click to select APK/XAPK files',
      'packages_selected': '{count} packages selected',
      'selected_packages': 'Selected packages ({count})',
      'remove_package': 'Remove package',
      'install_button': 'Install to Device',
      'installing': 'Installing application...',
      'installation_success': 'Installation Completed Successfully!',
      'installation_failed': 'Installation Failed: {error}',
      'apk_details': 'Package Details',
      'no_media_found': 'No photos or videos found on device.',
      'latest_media_title': 'Filter Latest Photos & Videos',
      'media_load_success': 'Loaded {count} items from device.',
      'selected_count': 'Selected {count} items',
      'select_latest': 'Select latest:',
      'copying_media': 'Copying selected media to PC...',
      'copy_media_success': 'Successfully copied {count} files to {dir}',
      'copy_media_failed': 'Failed to copy files: {error}',
      'device_info': 'Device Info',
      'language': 'Language',
      'theme': 'Theme',
      'confirm_delete': 'Confirm Delete',
      'confirm_delete_msg':
          'Are you sure you want to delete "{name}"? This cannot be undone.',
      'create_folder': 'Create Folder',
      'folder_name': 'Folder Name',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'create': 'Create',
      'save_settings': 'Save Settings',
      'settings_saved': 'Settings saved successfully!',
      'glass_settings_title': 'Glassmorphism',
      'glass_settings_subtitle': 'Customize blur & transparency',
      'glass_preview': 'Glassmorphism preview',
      'bg_blur_label': 'Main background blur',
      'bg_opacity_label': 'Main background opacity',
      'dialog_blur_label': 'Dialog blur',
      'dialog_opacity_label': 'Dialog opacity',
      'reset_defaults': 'Default',
      'user_guide': 'User Guide',
      'default_search_btn': 'Auto-detect Paths',
      'devices_found': '{count} devices found',
      'no_devices_found':
          'No devices found. Enable USB Debugging on your phone.',
      'wireless_adb': 'Wireless ADB',
      'wireless_adb_title': 'Connect over Wi-Fi',
      'wireless_adb_hint': 'Enter the device IP address and ADB port.',
      'wireless_host': 'Device IP address',
      'wireless_port': 'ADB port',
      'wireless_connect': 'Connect',
      'wireless_disconnect': 'Disconnect',
      'wireless_saved_endpoints': 'Saved endpoints',
      'wireless_no_endpoints': 'No saved wireless endpoints.',
      'wireless_fix_port_card_title': 'Fix Port 5555 & Switch to Wi-Fi',
      'wireless_fix_port_card_subtitle':
          'Set persistent port 5555, restart adbd in TCP/IP, and connect wirelessly in 1 click.',
      'wireless_fix_port_target_device': 'Target device:',
      'wireless_fix_port_detected_ip': 'Detected Wi-Fi IP:',
      'wireless_fix_port_btn': 'Fix Port 5555 & Connect',
      'wireless_fix_port_detecting_ip': 'Detecting IP...',
      'wireless_fix_port_no_usb_hint':
          'Connect a device via USB once to enable and fix port 5555, then you can disconnect the cable and connect wirelessly anytime.',
      'wireless_fix_port_unplug_hint':
          'Connected successfully! You can now safely unplug the USB cable.',
      'wireless_manual_connect_header': 'Manual IP / Port Connection',
      'wireless_refresh_ip_tooltip': 'Refresh Wi-Fi IP',
      'quick_tool_fix_port_title': 'Fix Port 5555 (Wi-Fi)',
      'quick_tool_fix_port_subtitle': 'adb tcpip 5555 & auto-connect',
      'diagnostics': 'Diagnostics',
      'diagnostics_title': 'Diagnostics Center',
      'diagnostics_hint': 'Check the local tools and device connection.',
      'diagnostics_run': 'Run diagnostics',
      'diagnostics_copy': 'Copy report',
      'diagnostics_no_report': 'Run a diagnostic check to see the report.',
      'workspace': 'Workspace',
      'workspace_title': 'Device Workspaces',
      'workspace_save_current': 'Save current device',
      'workspace_name': 'Workspace name',
      'workspace_empty': 'No saved workspaces.',
      'workspace_apply': 'Open',
      'workspace_delete': 'Delete',
      'workspace_saved': 'Workspace saved.',
      'command_palette': 'Command Palette',
      'command_palette_hint': 'Search commands…',
      'backup_restore': 'Backup & Restore',
      'backup_settings': 'Backup settings',
      'restore_settings': 'Restore settings',
      'backup_hint':
          'Export or restore paths, UI preferences, sync settings, profiles and workspaces.',
      'backup_exported': 'Settings backup exported.',
      'backup_imported':
          'Settings restored. Restart the app if a path does not update immediately.',
      'backup_failed': 'Could not export settings backup.',
      'backup_import_failed': 'Could not restore this backup file.',
      'check_updates': 'Check for updates',
      'update_title': 'Software Updates',
      'update_checking': 'Checking GitHub Releases…',
      'update_available': 'Version {version} is available.',
      'update_up_to_date': 'You are up to date ({version}).',
      'update_unavailable': 'Could not check GitHub Releases right now.',
      'open_release': 'Open release',
      'retry': 'Retry',
      'ota_update_title': 'LAN OTA Software Update',
      'ota_server_path': 'Server Path (SMB / UNC)',
      'ota_server_path_hint':
          r'\\10.81.141.226\temp\FBT\JA_PROJECT\JA_Update\JA_adb_tool',
      'ota_username': 'Username',
      'ota_password': 'Password',
      'ota_check_interval': 'Check Frequency',
      'ota_interval_startup': 'On Startup',
      'ota_interval_daily': 'Daily',
      'ota_interval_weekly': 'Weekly',
      'ota_interval_monthly': 'Monthly',
      'ota_interval_off': 'Disabled',
      'ota_test_connection': 'Test Connection',
      'ota_connection_success': 'Server connection successful!',
      'ota_connection_failed': 'Failed to connect to server: {error}',
      'ota_checking': 'Checking for updates on LAN server…',
      'ota_no_update': 'You are using the latest version ({version}).',
      'ota_update_available': 'New update available: {version}',
      'ota_update_now': 'Update Now',
      'ota_updating': 'Updating application…',
      'ota_downloading': 'Downloading update package…',
      'ota_extracting': 'Extracting update package…',
      'ota_restart_ready': 'Ready to apply! Restarting now…',
      'ota_update_failed': 'Update failed: {error}',
      'ota_save_config': 'Save OTA Settings',
      'ota_config_saved': 'OTA settings saved successfully.',
      'ota_browse_folder': 'Select Server Folder',
      'ota_package_size': 'Package size: {size}',
      'ota_release_date': 'Release date: {date}',
      'ota_release_notes': 'Release Notes',
      'ota_latest_version': 'Latest Version',
      'ota_current_version': 'Current Version',
      'ota_tab_title': 'LAN OTA Update',
      'plugin_manager': 'Plugin Manager',
      'plugin_empty':
          'No plugin manifests found. Add trusted JSON manifests to the app data plugins folder.',
      'current_path': 'Current path: {path}',
      'quick_tools_tab': 'Quick Tools',
      'settings_shortcuts': 'Settings Shortcuts',
      'launcher_settings': 'Default Launcher',
      'lock_settings': 'Lock & Pass Settings',
      'language_settings': 'Device Language',
      'developer_options': 'Developer Options',
      'wifi_settings': 'Wi-Fi Settings',
      'display_settings': 'Display Settings',
      'accessibility_settings': 'Accessibility',
      'app_settings': 'Manage Apps',
      'about_phone': 'About Phone',
      'device_controls': 'Device Power Controls',
      'reboot_system': 'Reboot System',
      'reboot_system_sub': 'Normal restart',
      'reboot_bootloader': 'Reboot Fastboot',
      'reboot_bootloader_sub': 'Fastboot mode',
      'reboot_recovery': 'Reboot Recovery',
      'reboot_recovery_sub': 'Recovery mode',
      'power_off': 'Power Off',
      'power_off_sub': 'Shutdown device',
      'ntp_time_sync_title': 'NTP Time Sync & Diagnostics',
      'ntp_time_sync_subtitle': 'Intranet NTP server & clock sync',
      'date_settings': 'Date & Time Settings',
      'ntp_device_clock_title': 'System Clock Status',
      'ntp_device_time': 'Device Time',
      'ntp_pc_time': 'PC Time',
      'ntp_drift_label': 'Time Drift',
      'ntp_drift_synced': 'Synchronized',
      'ntp_sync_to_pc_btn': 'Sync to PC Clock (1-Click)',
      'ntp_sync_to_pc_success':
          'Device clock synchronized to PC time successfully!',
      'ntp_sync_to_pc_failed': 'Failed to synchronize device clock to PC time.',
      'ntp_server_config_title': 'NTP Server Configuration',
      'ntp_current_server': 'Current Server:',
      'ntp_server_input_hint': 'NTP server host or IP (e.g. 10.81.184.80)',
      'ntp_presets_foxconn': 'Intranet / Foxconn Presets',
      'ntp_presets_public': 'Public Presets',
      'ntp_test_btn': 'Test Server (UDP 123 & Ping)',
      'ntp_apply_sync_btn': 'Apply & Sync (auto_time)',
      'ntp_server_test_success':
          'NTP server active! Latency: {ms}ms | Stratum: {stratum}',
      'ntp_server_test_failed': 'NTP server test failed: {error}',
      'ntp_apply_success': 'NTP server updated and time sync triggered!',
      'ntp_apply_failed': 'Failed to update NTP server on device.',
      'ntp_subnet_scanner_title': 'Intranet Subnet NTP Auto-Discovery',
      'ntp_subnet_input_hint': 'Subnet prefix (e.g. 10.81.184)',
      'ntp_scan_btn': 'Scan Subnet (/24)',
      'ntp_scanning': 'Scanning 254 IPs...',
      'ntp_no_servers_found': 'No responsive NTP servers found in this subnet.',
      'ntp_servers_found': 'Found {count} active NTP server(s):',
      'ntp_use_server_btn': 'Use',
      'ntp_diagnostics_title': 'Time Diagnostics & Logs',
      'ntp_view_diagnostics_btn': 'Fetch Diagnostics',
      'hardware_keys': 'Hardware Key Simulation',
      'key_back': 'Back',
      'key_home': 'Home',
      'key_recents': 'Recents',
      'key_power': 'Power Screen',
      'key_volume_up': 'Vol +',
      'key_volume_down': 'Vol -',
      'text_input_tool': 'Text Input Sender',
      'text_input_placeholder':
          'Type text to send to active input field on device...',
      'send_text': 'Send to Device',
      'text_input_tab': 'Text Input',
      'adb_command_tab': 'ADB Command',
      'adb_command_placeholder':
          'Enter ADB command (e.g. getprop or shell pm list packages)...',
      'run_command_btn': 'Run Command',
      'clear_console_btn': 'Clear Console',
      'console_output_label': 'Console Output',
      'command_history_label': 'History:',
      'select_history_hint': 'Select from history...',
      'confirm_reboot': 'Confirm Reboot',
      'confirm_reboot_msg': 'Are you sure you want to reboot the device?',
      'confirm_power_off': 'Confirm Power Off',
      'confirm_power_off_msg': 'Are you sure you want to power off the device?',
      'app_freeze_tab': 'App Manager',
      'uninstall_btn': 'Uninstall',
      'force_stop_btn': 'Force Stop',
      'clear_data_btn': 'Clear Data',
      'launch_app_btn': 'Launch App',
      'extract_apk_btn': 'Extract APK / XAPK',
      'batch_extract_apk': 'Extract APK/XAPK for selected',
      'extract_apk_success': 'Successfully extracted {app} to {file}',
      'extract_apk_failed': 'Failed to extract APK/XAPK for {app}',
      'batch_extract_success': 'Successfully extracted {count} apps',
      'open_folder': 'Open Folder',
      'file_transfer_completed': 'File transfer completed successfully!',
      'file_transfer_failed': 'File transfer failed or was cancelled.',
      'uninstall_confirm': 'Are you sure you want to uninstall {app}?',
      'clear_data_confirm': 'Are you sure you want to clear data for {app}?',
      'search_apps_placeholder': 'Search by name or package...',
      'freeze_btn': 'Freeze',
      'unfreeze_btn': 'Unfreeze',
      'show_system_apps': 'Show System Apps',
      'refresh_list': 'Refresh List',
      'sort_apps_tooltip': 'Sort apps',
      'sort_by_name': 'Sort by Name',
      'sort_by_newest': 'Sort by Newest',
      'sort_by_oldest': 'Sort by Oldest',
      'no_apps_found': 'No applications found.',
      'select_all_apps': 'Select all visible apps',
      'batch_actions': 'Batch actions',
      'table_name': 'Name',
      'table_size': 'Size',
      'table_modified': 'Date Modified',
      'table_actions': 'Actions',
      'search_files_hint': 'Filter files...',
      'empty_folder': 'This folder is empty',
      'app_inspector': 'App Inspector',
      'no_app_selected':
          'Select an application from the list to inspect details and perform actions.',
      'app_summary_total': 'Total Apps',
      'app_summary_user': 'User Apps',
      'app_summary_system': 'System Apps',
      'app_summary_frozen': 'Frozen Apps',
      'action_launch': 'Launch App',
      'action_force_stop': 'Force Stop',
      'action_clear_data': 'Clear Data',
      'action_uninstall': 'Uninstall',
      'action_extract_apk': 'Extract APK',
      'action_clone_app': 'Clone App',
      'app_cloner_title': 'App Cloner Studio',
      'app_cloner_subtitle':
          'Clone apps into standalone APKs or run in a native Dual Space',
      'clone_tab_apk': 'APK File Clone (Standalone)',
      'clone_tab_dual_space': 'Dual Space (Multi-User)',
      'target_app': 'Target Application',
      'new_app_name_label': 'Cloned App Name',
      'new_package_id_label': 'Cloned Package ID',
      'install_after_clone': 'Install directly to device after cloning',
      'save_to_pc': 'Save cloned APK to PC folder',
      'choose_export_folder': 'Choose Export Directory',
      'start_cloning_btn': 'Start Cloning',
      'cloning_in_progress': 'Cloning application in progress...',
      'cloning_success': 'Application cloned successfully!',
      'cloning_failed': 'Application cloning failed',
      'dual_space_guide_title': 'Dual Space Architecture (Instant & Secure)',
      'dual_space_guide_desc':
          'Leverages Android native Multi-User Work Profiles. Instant 1-second cloning, preserves 100% original signature, perfectly compatible with high-security apps (Zalo, Banking, Games).',
      'device_profiles_title': 'Current Device Profiles',
      'create_dual_space_btn': 'Create New Dual Space Profile',
      'install_to_space_btn': 'Clone to this Space',
      'launch_in_space_btn': 'Launch in Space',
      'remove_from_space_btn': 'Remove from Space',
      'no_dual_space_found':
          'No secondary clone profile found on this device. Click below to create one.',
      'clone_app_action': 'Clone App',
      'clone_apk_file': 'Clone APK File',
      'installer_tips_title': 'Fast & Smart Package Installer',
      'installer_tips_subtitle':
          'Easily sideload Android applications with advanced control',
      'installer_tip_1_title': 'Batch Installation',
      'installer_tip_1_desc':
          'Drag & drop multiple APK or XAPK files at once to queue them.',
      'installer_tip_2_title': 'Direct ADB Streaming',
      'installer_tip_2_desc':
          'Packages are pushed and verified directly over USB / Wireless ADB without device confirmation prompts.',
      'installer_tip_3_title': 'Split APK & Bundles',
      'installer_tip_3_desc':
          'Supports pure APKs, bundled APK sets, and Obb / Asset packs embedded inside XAPKs.',
      'clear_queue': 'Clear Queue',
      'install_to_device': 'Install to Device',
      'apk_inspector': 'Package Inspector',
      'packages_queued': '{count} packages queued',
      'media_filter_all': 'All Media',
      'media_filter_photos': 'Photos',
      'media_filter_videos': 'Videos',
      'scan_media_store': 'Scan Media Store',
      'preview_open': 'Preview & Open',
      'quick_select_presets': 'Quick Select',
      'sync_pathway_title': 'Sync Pathway',
      'sync_pc_target': 'PC Folder',
      'sync_android_target': 'Android Folder',
      'sync_overview_title': 'Sync Overview & Guide',
      'sync_overview_desc':
          'High-performance bidirectional file synchronization over ADB protocol.',
      'sync_mirror_notice':
          'Mirror Mode (Delete Extra): Deletes files in target that do not exist in source.',
      'sync_ready_idle':
          'Configure your source and destination folders, then click Start Sync.',
      'batch_freeze': 'Freeze selected',
      'batch_unfreeze': 'Unfreeze selected',
      'batch_force_stop': 'Force stop selected',
      'batch_uninstall': 'Uninstall selected',
      'batch_uninstall_confirm':
          'Uninstall {count} selected applications? This cannot be undone.',
      'batch_result': 'Completed: {success}; failed: {failed}',
      'reverse_tethering_title': 'Reverse Tethering (Gnirehtet)',
      'reverse_tethering_desc':
          'Share your computer\'s internet connection with your Android device via USB.',
      'start_reverse_tethering': 'Start Reverse Tethering',
      'stop_reverse_tethering': 'Stop Reverse Tethering',
      'gnirehtet_path': 'Gnirehtet Executable Path',
      'reverse_tethering_active': 'Reverse Tethering Active',
      'reverse_tethering_inactive': 'Reverse Tethering Inactive',
      'vpn_instruction':
          'Please unlock your device and approve the VPN connection permission prompt after starting.',
      'gnirehtet_logs': 'Gnirehtet Connection Logs',
      'about': 'About',
      'about_version': 'Version',
      'about_desc':
          'A Windows-first Android device management toolkit with Bento Liquid Glass UI, ADB/Scrcpy, wireless devices, diagnostics, workspaces, adaptive batch APK/XAPK installation, preloaded per-device Latest Media cache, Safe Sync v2, backup/restore, protected file downloads, device-pinned batch operations, and Gnirehtet reverse tethering with auto client installation.',
      'guide_title': 'How to Use',
      'guide_connect':
          '1. USB Driver & Connection: Install the USB driver for your Android device (e.g., Google or official OEM driver), then enable USB Debugging (ADB) in Developer Options on your phone before connecting via USB.',
      'guide_mirror':
          '2. Screen Mirror — Click "Launch Mirroring" to view and control your device screen on PC.',
      'guide_file':
          '3. File Explorer — Browse, upload, download, and delete files. Downloads replace existing local files only after success; use a new destination for an existing directory name.',
      'guide_sync':
          '4. Safe Sync v2 — Preview copies, updates, and deletions before syncing. Mirror Sync requires typing DELETE to confirm the exact destructive diff. Running sync keeps its original device target when you switch devices.',
      'guide_media':
          '5. Latest Media — Media starts loading after device discovery and is cached per device when switching; use Refresh for a fresh query.',
      'guide_install':
          '6. App Installer — On desktop, use the two-column layout: picker and queue on the left, details and an expanding readable log on the right. Select multiple APK/XAPK files, review the queue, then install them sequentially; archives are validated before extraction. All packages keep the original device target.',
      'guide_tether':
          '7. Reverse Tethering — Share your PC internet connection with the device via Gnirehtet. Client APK is automatically detected and installed via ADB if missing.',
      'guide_tools':
          '8. Quick Tools — Send text, simulate keys, reboot, take screenshots, and more.',
      'guide_settings':
          '9. Productivity & settings — Configure tool paths, save Scrcpy profiles, connect over Wireless ADB, inspect Diagnostics and Device Workspaces, use Ctrl+K Command Palette, export/restore settings, and check GitHub Releases. The selected language is remembered between launches; debug.bat enables diagnostic timestamps.',
      'about_close': 'Close',
      'about_made_by': 'Made with ❤️ by JA Team',
      'project_website': 'Project website',
      'source_code': 'Source code',
      'open_link_failed': 'Unable to open the link.',
      'sync_folders_btn': 'Folder Sync',
      'sync_folders_title': 'Sync PC & Android Folders',
      'pc_folder_label': 'PC Folder:',
      'android_folder_label': 'Android Folder:',
      'sync_direction_label': 'Direction:',
      'sync_direction_pc_to_android': 'PC -> Android (Upload/Overwrite)',
      'sync_direction_android_to_pc': 'Android -> PC (Download/Overwrite)',
      'sync_direction_newest': 'Sync by Newest File (Skip duplicates)',
      'auto_sync_label': 'Auto-sync when device connected',
      'delete_extra_files_label': 'Delete extra files on target (Mirror Sync)',
      'start_sync_btn': 'Start Sync',
      'pause_sync_btn': 'Pause',
      'resume_sync_btn': 'Resume',
      'sync_status_idle': 'Configure paths and options, then click Start Sync.',
      'select_pc_folder_hint': 'Select PC folder...',
      'error_select_pc_folder': 'Please select a valid PC folder.',
      'recent_sync_title': 'Recent Configurations',
      'get_current_folder_btn': 'Get Current Folder',
      'copy_log_btn': 'Copy Log',
      'clear_log_btn': 'Clear Log',
      'sync_history_empty': 'No recent sync history.',
      'clear_history_btn': 'Clear History',
    },
    'vi': {
      'sync_history_summary': 'Hướng: {direction} | Phản chiếu: {mirror}',
      'yes_label': 'Có',
      'no_label': 'Không',
      'sync_status_label': 'Trạng thái: {status}',
      'sync_starting': 'Đang bắt đầu...',
      'sync_scanning': 'Đang quét...',
      'sync_comparing': 'Đang so sánh...',
      'sync_running': 'Đang đồng bộ...',
      'sync_completed': 'Hoàn tất',
      'sync_error': 'Lỗi',
      'sync_cancelled': 'Đã hủy',
      'sync_paused': 'Đã tạm dừng',
      'parent_directory': 'Về thư mục cha',
      'delete_selected_success': 'Đã xóa các mục đã chọn!',
      'delete_some_failed': 'Không thể xóa một số mục.',
      'create_directory_failed': 'Không thể tạo thư mục',
      'delete_item_failed': 'Không thể xóa mục.',
      'retry_action': 'Thử lại',
      'refresh_action': 'Làm mới',
      'rescan_media': 'Quét lại media',
      'media_scan_hint':
          'Quét chỉ mục media trên thiết bị để xem ảnh và video.',
      'split_apks_label': 'APK phân tách',
      'xapk_archive': 'Gói lưu trữ XAPK',
      'standalone_apk': 'APK độc lập',
      'target_device_ready': 'Thiết bị đích sẵn sàng',
      'android_device_label': 'Thiết bị Android',
      'sideload_hint': 'Chọn tệp APK hoặc XAPK phía trên để bắt đầu cài đặt.',
      'copied_package_id': 'Đã sao chép ID gói',
      'version_label': 'Phiên bản',
      'type_label': 'Loại',
      'terminal_log': 'Nhật ký terminal',
      'log_copied': 'Đã sao chép nhật ký',
      'installer_waiting': 'Sẵn sàng. Đang chờ bắt đầu cài đặt...',
      'copy_package_id': 'Sao chép ID gói',
      'system_app_badge': 'ỨNG DỤNG HỆ THỐNG',
      'user_app_badge': 'ỨNG DỤNG NGƯỜI DÙNG',
      'frozen_badge': 'ĐÃ ĐÓNG BĂNG',
      'active_badge': 'HOẠT ĐỘNG',
      'processing_label': 'Đang xử lý...',
      'sync_preview_failed': 'Không thể tạo bản xem trước đồng bộ.',
      'sync_preview_title': 'Xem trước đồng bộ',
      'files_to_delete': 'Tệp sẽ xóa',
      'confirm_delete_hint': 'Nhập DELETE để xác nhận',
      'browse_pc_folder': 'Chọn thư mục PC',
      'restore_configuration': 'Khôi phục cấu hình',
      'two_way_newest': 'Hai chiều (mới nhất)',
      'select_pc_directory': 'Chọn thư mục PC',
      'delta_sync_title': 'Đồng bộ thay đổi hai chiều',
      'delta_sync_hint':
          'Chỉ truyền tệp mới hoặc thay đổi dựa trên kích thước và thời gian sửa đổi để đồng bộ nhanh hơn.',
      'dry_run_title': 'Kiểm tra trước khi đồng bộ',
      'dry_run_hint':
          'Quét xem trước khi thay đổi tệp, cho biết số tệp sẽ được thêm hoặc cập nhật.',
      'mirror_mode_title': 'Chế độ phản chiếu (xóa tệp dư)',
      'console_log': 'Nhật ký console',
      'sync_waiting': 'Đang chờ bắt đầu đồng bộ...',
      'items_count': '{count} mục',
      'no_files_matching': 'Không có tệp khớp "{query}"',
      'error_details': 'Lỗi: {error}',
      'media_downloaded': 'Đã tải {count} tệp vào {path}',
      'media_partial_download':
          'Sao chép hoàn tất nhưng có cảnh báo. Kiểm tra thư mục: {path}',
      'media_folder_set': 'Thư mục tải media: {path}',
      'create_target_failed': 'Không thể tạo thư mục đích: {error}',
      'packages_prepared': 'Đã chuẩn bị {count} gói để cài đặt lần lượt.',
      'copied_value': 'Đã sao chép: {value}',
      'installed_time': 'Đã cài: {time}',
      'freeze_app_failed': 'Không thể đóng băng {app}',
      'unfreeze_app_failed': 'Không thể bỏ đóng băng {app}',
      'extracting_app': 'Đang trích xuất {app}...',
      'extracting_apps': 'Đang trích xuất {count} ứng dụng...',
      'sync_scanned': 'Đã quét {pc} tệp PC và {android} tệp Android.',
      'sync_copy_count': '{count} sao chép/cập nhật',
      'sync_delete_count': '{count} xóa',
      'sync_more_files': '… và {count} tệp khác',
      'app_title': 'JA ADB Tool',
      'no_device_connected': 'Chưa kết nối thiết bị',
      'select_device':
          'Vui lòng chọn một thiết bị Android từ thanh bên để bắt đầu.',
      'adb_setup_title': 'Bật USB Debugging',
      'adb_setup_subtitle': 'Thực hiện vài bước để kết nối điện thoại Android',
      'adb_image_disclaimer':
          'Ảnh minh họa dùng giao diện Android chung; tên mục có thể khác theo hãng điện thoại.',
      'adb_illustration_phone': 'Android',
      'adb_illustration_debug': 'Gỡ lỗi USB',
      'adb_image_zoom': 'Bấm để phóng to',
      'adb_step_1': 'Mở Cài đặt trên điện thoại.',
      'adb_step_2':
          'Mở Giới thiệu điện thoại, rồi chạm 7 lần vào Số bản dựng để bật Tùy chọn nhà phát triển.',
      'adb_step_3': 'Mở Tùy chọn nhà phát triển và bật Gỡ lỗi USB.',
      'adb_step_4':
          'Kết nối điện thoại bằng cáp USB, mở khóa và cho phép hộp thoại xác thực RSA.',
      'adb_setup_note':
          'Giữ điện thoại mở khóa khi kết nối, sau đó làm mới danh sách thiết bị.',
      'adb_refresh_button': 'Làm mới thiết bị',
      'refresh_devices': 'Làm mới danh sách',
      'scrcpy_tab': 'Xem màn hình',
      'file_explorer_tab': 'Quản lý tệp',
      'latest_media_tab': 'Ảnh & Video mới',
      'installer_tab': 'Cài đặt APK/XAPK',
      'settings_tab': 'Cài đặt nâng cao',
      'advanced_settings': 'Cài đặt nâng cao',
      'launch_mirror': 'Khởi chạy truyền hình',
      'launch_standalone_mirror': 'Mở cửa sổ rời (Đa thiết bị)',
      'stop_mirror': 'Dừng truyền hình',
      'take_screenshot': 'Chụp ảnh màn hình',
      'select_screenshot_folder': 'Chọn thư mục lưu ảnh chụp',
      'select_download_folder': 'Chọn thư mục tải ảnh/video',
      'predefined_label': 'Lệnh/Văn bản mẫu:',
      'select_predefined_hint': 'Chọn một mẫu...',
      'scrcpy_options': 'Tùy chọn hiển thị',
      'scrcpy_profiles': 'Profile Scrcpy',
      'scrcpy_profile_hint': 'Tên profile',
      'save_profile': 'Lưu profile',
      'delete_profile': 'Xóa profile',
      'profile_saved': 'Đã lưu profile Scrcpy.',
      'profile_delete_confirm': 'Xóa profile "{name}"?',
      'stay_on_top': 'Luôn ở trên cùng',
      'fullscreen': 'Toàn màn hình',
      'no_control': 'Chỉ xem (Không điều khiển)',
      'keep_awake': 'Giữ thiết bị không tắt màn hình',
      'borderless': 'Cửa sổ không viền',
      'disable_audio': 'Tắt âm thanh (Không thu âm)',
      'mirror_quality_preset': 'Chất lượng hình ảnh',
      'mirror_preset_low': 'Nhẹ / Wi-Fi',
      'mirror_preset_balanced': 'Cân bằng',
      'mirror_preset_high': 'Rõ nét / USB',
      'mirror_preset_low_desc': '1024px • 30fps • 3Mbps (Độ trễ thấp nhất)',
      'mirror_preset_balanced_desc': '1600px • 60fps • 6Mbps (Khuyên dùng)',
      'mirror_preset_high_desc': '1920px • 60fps • 10Mbps (Sắc nét qua cáp)',
      'mirror_starting': 'Đang kết nối...',
      'mirror_stopping': 'Đang dừng...',
      'mirror_initializing_hint':
          'Đang khởi tạo Scrcpy & đồng bộ khung hình...',
      'mirror_error_title': 'Không thể khởi chạy Screen Mirror',
      'mirror_open_standalone': 'Mở cửa sổ rời',
      'mirror_diagnostics': 'Thông tin Mirror',
      'pc_side': 'Máy tính (PC)',
      'android_side': 'Thiết bị Android',
      'download_selected': 'Tải xuống PC',
      'upload_files': 'Tải lên Android',
      'new_folder': 'Thư mục mới',
      'delete_selected': 'Xóa',
      'loading': 'Đang tải...',
      'status': 'Trạng thái',
      'path_to_adb': 'Đường dẫn adb.exe',
      'path_to_scrcpy': 'Đường dẫn scrcpy.exe',
      'path_settings_title': 'Đường dẫn công cụ',
      'path_settings_subtitle': 'Chỉ mở khi cần đổi ADB, Scrcpy hoặc Gnirehtet',
      'select_apk_xapk': 'Chọn tệp APK hoặc XAPK',
      'drag_drop_apk_xapk': 'Nhấp vào đây để chọn các tệp APK/XAPK',
      'packages_selected': 'Đã chọn {count} gói cài đặt',
      'selected_packages': 'Các gói đã chọn ({count})',
      'remove_package': 'Xóa gói',
      'install_button': 'Cài đặt vào thiết bị',
      'installing': 'Đang cài đặt ứng dụng...',
      'installation_success': 'Cài đặt thành công!',
      'installation_failed': 'Cài đặt thất bại: {error}',
      'apk_details': 'Chi tiết gói cài đặt',
      'no_media_found': 'Không tìm thấy ảnh hoặc video nào trên thiết bị.',
      'latest_media_title': 'Lọc ảnh & video mới nhất',
      'media_load_success': 'Đã tải {count} mục từ thiết bị.',
      'selected_count': 'Đã chọn {count} mục',
      'select_latest': 'Chọn mới nhất:',
      'copying_media': 'Đang sao chép các mục đã chọn sang PC...',
      'copy_media_success': 'Đã sao chép thành công {count} tệp vào {dir}',
      'copy_media_failed': 'Sao chép thất bại: {error}',
      'device_info': 'Thông tin thiết bị',
      'language': 'Ngôn ngữ',
      'theme': 'Giao diện',
      'confirm_delete': 'Xác nhận xóa',
      'confirm_delete_msg':
          'Bạn có chắc chắn muốn xóa "{name}"? Hành động này không thể hoàn tác.',
      'create_folder': 'Tạo thư mục',
      'folder_name': 'Tên thư mục',
      'cancel': 'Hủy',
      'confirm': 'Xác nhận',
      'create': 'Tạo mới',
      'save_settings': 'Lưu cấu hình',
      'settings_saved': 'Đã lưu cấu hình thành công!',
      'glass_settings_title': 'Glassmorphism',
      'glass_settings_subtitle': 'Tùy chỉnh độ mờ & độ trong suốt',
      'glass_preview': 'Xem trước Glassmorphism',
      'bg_blur_label': 'Độ mờ nền chính',
      'bg_opacity_label': 'Độ trong suốt nền chính',
      'dialog_blur_label': 'Độ mờ hộp thoại',
      'dialog_opacity_label': 'Độ trong suốt hộp thoại',
      'reset_defaults': 'Mặc định',
      'user_guide': 'Hướng dẫn sử dụng',
      'default_search_btn': 'Tự động tìm kiếm',
      'devices_found': 'Tìm thấy {count} thiết bị',
      'no_devices_found':
          'Không tìm thấy thiết bị. Hãy chắc chắn USB Debugging đã bật.',
      'wireless_adb': 'ADB không dây',
      'wireless_adb_title': 'Kết nối qua Wi-Fi',
      'wireless_adb_hint': 'Nhập địa chỉ IP và cổng ADB của thiết bị.',
      'wireless_host': 'Địa chỉ IP thiết bị',
      'wireless_port': 'Cổng ADB',
      'wireless_connect': 'Kết nối',
      'wireless_disconnect': 'Ngắt kết nối',
      'wireless_saved_endpoints': 'Thiết bị đã lưu',
      'wireless_no_endpoints': 'Chưa có thiết bị Wi-Fi đã lưu.',
      'wireless_fix_port_card_title': 'Cố định cổng 5555 & Chuyển sang Wi-Fi',
      'wireless_fix_port_card_subtitle':
          'Cố định cổng 5555 vĩnh viễn, khởi động lại adbd TCP/IP và tự động kết nối Wi-Fi 1-click.',
      'wireless_fix_port_target_device': 'Thiết bị mục tiêu:',
      'wireless_fix_port_detected_ip': 'IP Wi-Fi phát hiện:',
      'wireless_fix_port_btn': 'Cố định cổng 5555 & Kết nối',
      'wireless_fix_port_detecting_ip': 'Đang dò tìm IP...',
      'wireless_fix_port_no_usb_hint':
          'Cắm cáp USB một lần để kích hoạt và cố định cổng 5555, sau đó có thể rút cáp và kết nối không dây bất cứ lúc nào.',
      'wireless_fix_port_unplug_hint':
          'Kết nối thành công! Bây giờ bạn có thể an tâm rút cáp USB ra.',
      'wireless_manual_connect_header': 'Kết nối thủ công qua IP / Port',
      'wireless_refresh_ip_tooltip': 'Dò lại IP Wi-Fi',
      'quick_tool_fix_port_title': 'Cố định cổng 5555 (Wi-Fi)',
      'quick_tool_fix_port_subtitle': 'adb tcpip 5555 & tự kết nối',
      'diagnostics': 'Chẩn đoán',
      'diagnostics_title': 'Trung tâm chẩn đoán',
      'diagnostics_hint': 'Kiểm tra công cụ cục bộ và kết nối thiết bị.',
      'diagnostics_run': 'Chạy chẩn đoán',
      'diagnostics_copy': 'Sao chép báo cáo',
      'diagnostics_no_report': 'Chạy chẩn đoán để xem báo cáo.',
      'workspace': 'Workspace',
      'workspace_title': 'Workspace thiết bị',
      'workspace_save_current': 'Lưu thiết bị hiện tại',
      'workspace_name': 'Tên workspace',
      'workspace_empty': 'Chưa có workspace đã lưu.',
      'workspace_apply': 'Mở',
      'workspace_delete': 'Xóa',
      'workspace_saved': 'Đã lưu workspace.',
      'command_palette': 'Bảng lệnh',
      'command_palette_hint': 'Tìm kiếm lệnh…',
      'backup_restore': 'Sao lưu & Khôi phục',
      'backup_settings': 'Sao lưu cấu hình',
      'restore_settings': 'Khôi phục cấu hình',
      'backup_hint':
          'Xuất hoặc khôi phục đường dẫn, giao diện, đồng bộ, profile và workspace.',
      'backup_exported': 'Đã xuất bản sao cấu hình.',
      'backup_imported':
          'Đã khôi phục cấu hình. Hãy khởi động lại nếu đường dẫn chưa cập nhật ngay.',
      'backup_failed': 'Không thể xuất bản sao cấu hình.',
      'backup_import_failed': 'Không thể khôi phục tệp sao lưu này.',
      'check_updates': 'Kiểm tra cập nhật',
      'update_title': 'Cập nhật phần mềm',
      'update_checking': 'Đang kiểm tra GitHub Releases…',
      'update_available': 'Đã có phiên bản {version}.',
      'update_up_to_date': 'Bạn đang dùng bản mới nhất ({version}).',
      'update_unavailable': 'Chưa thể kiểm tra GitHub Releases lúc này.',
      'open_release': 'Mở release',
      'retry': 'Thử lại',
      'ota_update_title': 'Cập nhật phần mềm qua mạng LAN (OTA)',
      'ota_server_path': 'Đường dẫn máy chủ (SMB / UNC)',
      'ota_server_path_hint':
          r'\\10.81.141.226\temp\FBT\JA_PROJECT\JA_Update\JA_adb_tool',
      'ota_username': 'Tên đăng nhập',
      'ota_password': 'Mật khẩu',
      'ota_check_interval': 'Tần suất kiểm tra',
      'ota_interval_startup': 'Khi khởi động',
      'ota_interval_daily': 'Hàng ngày',
      'ota_interval_weekly': 'Hàng tuần',
      'ota_interval_monthly': 'Hàng tháng',
      'ota_interval_off': 'Tắt tự động',
      'ota_test_connection': 'Kiểm tra kết nối',
      'ota_connection_success': 'Kết nối máy chủ thành công!',
      'ota_connection_failed': 'Không thể kết nối máy chủ: {error}',
      'ota_checking': 'Đang kiểm tra cập nhật trên máy chủ LAN…',
      'ota_no_update': 'Bạn đang sử dụng phiên bản mới nhất ({version}).',
      'ota_update_available': 'Đã có phiên bản mới: {version}',
      'ota_update_now': 'Cập nhật ngay',
      'ota_updating': 'Đang tiến hành cập nhật…',
      'ota_downloading': 'Đang tải gói cập nhật…',
      'ota_extracting': 'Đang giải nén gói cập nhật…',
      'ota_restart_ready': 'Sẵn sàng áp dụng! Khởi động lại ngay…',
      'ota_update_failed': 'Cập nhật thất bại: {error}',
      'ota_save_config': 'Lưu cài đặt OTA',
      'ota_config_saved': 'Đã lưu cài đặt OTA thành công.',
      'ota_browse_folder': 'Chọn thư mục máy chủ',
      'ota_package_size': 'Kích thước gói: {size}',
      'ota_release_date': 'Ngày phát hành: {date}',
      'ota_release_notes': 'Nhật ký thay đổi',
      'ota_latest_version': 'Phiên bản mới',
      'ota_current_version': 'Phiên bản hiện tại',
      'ota_tab_title': 'Cập nhật OTA',
      'plugin_manager': 'Quản lý plugin',
      'plugin_empty':
          'Chưa có plugin manifest. Chỉ thêm JSON manifest đáng tin cậy vào thư mục plugins của app.',
      'current_path': 'Đường dẫn hiện tại: {path}',
      'quick_tools_tab': 'Tính năng nhanh',
      'settings_shortcuts': 'Phím tắt Cài đặt',
      'launcher_settings': 'Launcher mặc định',
      'lock_settings': 'Khóa màn hình & Mật khẩu',
      'language_settings': 'Ngôn ngữ thiết bị',
      'developer_options': 'Tùy chọn nhà phát triển',
      'wifi_settings': 'Cài đặt Wi-Fi',
      'display_settings': 'Cài đặt màn hình',
      'accessibility_settings': 'Hỗ trợ tiếp cận',
      'app_settings': 'Quản lý ứng dụng',
      'about_phone': 'Thông tin điện thoại',
      'device_controls': 'Điều khiển & Khởi động',
      'reboot_system': 'Khởi động lại',
      'reboot_system_sub': 'Khởi động lại bình thường',
      'reboot_bootloader': 'Vào Fastboot',
      'reboot_bootloader_sub': 'Chế độ Fastboot',
      'reboot_recovery': 'Vào Recovery',
      'reboot_recovery_sub': 'Chế độ Recovery',
      'power_off': 'Tắt nguồn',
      'power_off_sub': 'Tắt nguồn thiết bị',
      'ntp_time_sync_title': 'Cấu hình & Đồng bộ NTP',
      'ntp_time_sync_subtitle': 'Máy chủ NTP nội bộ & chỉnh giờ chuẩn',
      'date_settings': 'Cài đặt Ngày & Giờ',
      'ntp_device_clock_title': 'Trạng thái Giờ Hệ Thống',
      'ntp_device_time': 'Giờ Thiết Bị',
      'ntp_pc_time': 'Giờ Máy Tính',
      'ntp_drift_label': 'Độ lệch thời gian',
      'ntp_drift_synced': 'Đã chuẩn giờ',
      'ntp_sync_to_pc_btn': 'Đồng bộ ngay theo giờ PC (1-Click)',
      'ntp_sync_to_pc_success':
          'Đã đồng bộ giờ thiết bị theo máy tính thành công!',
      'ntp_sync_to_pc_failed': 'Không thể đồng bộ giờ thiết bị theo máy tính.',
      'ntp_server_config_title': 'Cấu hình Máy chủ NTP',
      'ntp_current_server': 'Máy chủ hiện tại:',
      'ntp_server_input_hint': 'IP hoặc tên máy chủ NTP (vd: 10.81.184.80)',
      'ntp_presets_foxconn': 'Mẫu Nội bộ / Foxconn',
      'ntp_presets_public': 'Mẫu Công cộng',
      'ntp_test_btn': 'Kiểm tra máy chủ (UDP 123 & Ping)',
      'ntp_apply_sync_btn': 'Áp dụng & Đồng bộ (auto_time)',
      'ntp_server_test_success':
          'Máy chủ NTP hoạt động tốt! Độ trễ: {ms}ms | Stratum: {stratum}',
      'ntp_server_test_failed': 'Kiểm tra máy chủ NTP thất bại: {error}',
      'ntp_apply_success': 'Đã cập nhật máy chủ NTP và kích hoạt đồng bộ giờ!',
      'ntp_apply_failed': 'Không thể cập nhật máy chủ NTP trên thiết bị.',
      'ntp_subnet_scanner_title': 'Quét Dò NTP Trong Mạng Nội Bộ',
      'ntp_subnet_input_hint': 'Tiền tố dải mạng (vd: 10.81.184)',
      'ntp_scan_btn': 'Quét dải mạng (/24)',
      'ntp_scanning': 'Đang quét 254 IP...',
      'ntp_no_servers_found':
          'Không tìm thấy máy chủ NTP nào phản hồi trong dải này.',
      'ntp_servers_found': 'Tìm thấy {count} máy chủ NTP đang hoạt động:',
      'ntp_use_server_btn': 'Dùng',
      'ntp_diagnostics_title': 'Nhật ký chẩn đoán & Log',
      'ntp_view_diagnostics_btn': 'Lấy log chẩn đoán',
      'hardware_keys': 'Phím điều hướng ảo',
      'key_back': 'Trở về (Back)',
      'key_home': 'Trang chủ (Home)',
      'key_recents': 'Gần đây (Recents)',
      'key_power': 'Nút Nguồn',
      'key_volume_up': 'Tăng Âm',
      'key_volume_down': 'Giảm Âm',
      'text_input_tool': 'Công cụ nhập văn bản nhanh',
      'text_input_placeholder':
          'Nhập văn bản cần gửi tới ô nhập liệu trên điện thoại...',
      'send_text': 'Gửi tới điện thoại',
      'text_input_tab': 'Gửi văn bản',
      'adb_command_tab': 'Lệnh ADB',
      'adb_command_placeholder':
          'Nhập lệnh ADB (ví dụ: getprop hoặc shell pm list packages)...',
      'run_command_btn': 'Chạy lệnh',
      'clear_console_btn': 'Xóa Console',
      'console_output_label': 'Kết quả Console',
      'command_history_label': 'Lịch sử:',
      'select_history_hint': 'Chọn lệnh từ lịch sử...',
      'confirm_reboot': 'Xác nhận khởi động lại',
      'confirm_reboot_msg':
          'Bạn có chắc chắn muốn khởi động lại thiết bị không?',
      'confirm_power_off': 'Xác nhận tắt nguồn',
      'confirm_power_off_msg':
          'Bạn có chắc chắn muốn tắt nguồn thiết bị không?',
      'app_freeze_tab': 'Quản lý ứng dụng',
      'uninstall_btn': 'Gỡ cài đặt',
      'force_stop_btn': 'Buộc dừng',
      'clear_data_btn': 'Xóa dữ liệu',
      'launch_app_btn': 'Mở ứng dụng',
      'extract_apk_btn': 'Trích xuất APK / XAPK',
      'batch_extract_apk': 'Trích xuất APK/XAPK đã chọn',
      'extract_apk_success': 'Đã trích xuất thành công {app} thành {file}',
      'extract_apk_failed': 'Trích xuất APK/XAPK cho {app} thất bại',
      'batch_extract_success': 'Đã trích xuất thành công {count} ứng dụng',
      'open_folder': 'Mở thư mục',
      'file_transfer_completed': 'Truyền tệp đã hoàn tất thành công!',
      'file_transfer_failed': 'Truyền tệp thất bại hoặc đã bị huỷ.',
      'uninstall_confirm': 'Bạn có chắc chắn muốn gỡ cài đặt {app} không?',
      'clear_data_confirm':
          'Bạn có chắc chắn muốn xóa dữ liệu của {app} không?',
      'search_apps_placeholder': 'Tìm theo tên hoặc package...',
      'freeze_btn': 'Đóng băng',
      'unfreeze_btn': 'Rã đông',
      'show_system_apps': 'Hiện ứng dụng hệ thống',
      'refresh_list': 'Làm mới danh sách',
      'sort_apps_tooltip': 'Sắp xếp ứng dụng',
      'sort_by_name': 'Sắp xếp theo Tên',
      'sort_by_newest': 'Sắp xếp theo Ngày mới nhất',
      'sort_by_oldest': 'Sắp xếp theo Ngày cũ nhất',
      'no_apps_found': 'Không tìm thấy ứng dụng.',
      'select_all_apps': 'Chọn tất cả ứng dụng đang hiển thị',
      'batch_actions': 'Thao tác hàng loạt',
      'table_name': 'Tên tệp',
      'table_size': 'Kích thước',
      'table_modified': 'Ngày sửa đổi',
      'table_actions': 'Thao tác',
      'search_files_hint': 'Lọc tệp tin...',
      'empty_folder': 'Thư mục này trống',
      'app_inspector': 'Chi tiết ứng dụng',
      'no_app_selected':
          'Chọn một ứng dụng từ danh sách để xem chi tiết và thực hiện thao tác.',
      'app_summary_total': 'Tổng số ứng dụng',
      'app_summary_user': 'Ứng dụng người dùng',
      'app_summary_system': 'Ứng dụng hệ thống',
      'app_summary_frozen': 'Đang đóng băng',
      'action_launch': 'Khởi chạy',
      'action_force_stop': 'Buộc dừng',
      'action_clear_data': 'Xóa dữ liệu',
      'action_uninstall': 'Gỡ cài đặt',
      'action_extract_apk': 'Trích xuất APK',
      'action_clone_app': 'Nhân bản ứng dụng',
      'app_cloner_title': 'Trình Nhân Bản Ứng Dụng (App Cloner Studio)',
      'app_cloner_subtitle':
          'Nhân bản ứng dụng thành file APK độc lập hoặc chạy qua Không gian song song',
      'clone_tab_apk': 'Nhân bản file APK (Độc lập)',
      'clone_tab_dual_space': 'Không gian Song song (Dual Space)',
      'target_app': 'Ứng dụng mục tiêu',
      'new_app_name_label': 'Tên ứng dụng nhân bản',
      'new_package_id_label': 'Package ID nhân bản',
      'install_after_clone': 'Cài đặt trực tiếp vào thiết bị sau khi nhân bản',
      'save_to_pc': 'Lưu tệp APK nhân bản ra máy tính',
      'choose_export_folder': 'Chọn thư mục lưu APK',
      'start_cloning_btn': 'Bắt đầu nhân bản',
      'cloning_in_progress': 'Đang tiến hành nhân bản ứng dụng...',
      'cloning_success': 'Nhân bản ứng dụng thành công!',
      'cloning_failed': 'Nhân bản ứng dụng thất bại',
      'dual_space_guide_title':
          'Cơ chế Không gian Song song (Siêu tốc & An toàn)',
      'dual_space_guide_desc':
          'Tận dụng cấu trúc Multi-User Work Profile native của Android. Nhân bản tức thì trong 1 giây, giữ nguyên 100% chữ ký gốc, an toàn tuyệt đối cho ứng dụng bảo mật cao (Zalo, Banking, Games).',
      'device_profiles_title': 'Các Không gian hiện có trên máy',
      'create_dual_space_btn': 'Tạo Không gian Song song mới',
      'install_to_space_btn': 'Nhân bản vào Không gian này',
      'launch_in_space_btn': 'Khởi chạy trong Không gian',
      'remove_from_space_btn': 'Gỡ khỏi Không gian',
      'no_dual_space_found':
          'Chưa có Không gian song song phụ nào trên thiết bị này. Bấm nút dưới để tạo mới.',
      'clone_app_action': 'Nhân bản ứng dụng',
      'clone_apk_file': 'Nhân bản tệp APK',
      'installer_tips_title': 'Trình Cài Đặt Gói Thông Minh',
      'installer_tips_subtitle':
          'Cài đặt ứng dụng Android nhanh chóng với kiểm soát nâng cao',
      'installer_tip_1_title': 'Cài đặt hàng loạt',
      'installer_tip_1_desc':
          'Kéo thả nhiều tệp APK hoặc XAPK cùng lúc vào danh sách hàng đợi.',
      'installer_tip_2_title': 'Truyền trực tiếp qua ADB',
      'installer_tip_2_desc':
          'Gói được truyền và cài đặt thẳng qua USB / Wi-Fi mà không cần mở máy xác nhận thủ công.',
      'installer_tip_3_title': 'Hỗ trợ Split APK & Gói Bundle',
      'installer_tip_3_desc':
          'Hỗ trợ đầy đủ tệp APK tiêu chuẩn, bộ bundle chia nhỏ và tài nguyên Obb bên trong file XAPK.',
      'clear_queue': 'Xóa hàng đợi',
      'install_to_device': 'Cài đặt vào thiết bị',
      'apk_inspector': 'Kiểm tra gói cài đặt',
      'packages_queued': '{count} gói trong hàng đợi',
      'media_filter_all': 'Tất cả',
      'media_filter_photos': 'Ảnh',
      'media_filter_videos': 'Video',
      'scan_media_store': 'Quét kho tệp Media',
      'preview_open': 'Xem trước & Mở',
      'quick_select_presets': 'Chọn nhanh',
      'sync_pathway_title': 'Lộ trình đồng bộ',
      'sync_pc_target': 'Thư mục PC',
      'sync_android_target': 'Thư mục Android',
      'sync_overview_title': 'Tổng quan & Hướng dẫn đồng bộ',
      'sync_overview_desc':
          'Đồng bộ hóa tệp tin hai chiều hiệu năng cao qua giao thức ADB.',
      'sync_mirror_notice':
          'Chế độ Mirror (Xóa file thừa): Xóa các tệp ở đích nếu không tồn tại ở nguồn.',
      'sync_ready_idle':
          'Thiết lập thư mục nguồn và đích, sau đó bấm Bắt đầu đồng bộ.',
      'batch_freeze': 'Đóng băng mục đã chọn',
      'batch_unfreeze': 'Rã đông mục đã chọn',
      'batch_force_stop': 'Buộc dừng mục đã chọn',
      'batch_uninstall': 'Gỡ cài đặt mục đã chọn',
      'batch_uninstall_confirm':
          'Gỡ cài đặt {count} ứng dụng đã chọn? Thao tác này không thể hoàn tác.',
      'batch_result': 'Hoàn tất: {success}; thất bại: {failed}',
      'reverse_tethering_title': 'Chia sẻ mạng đảo chiều (Gnirehtet)',
      'reverse_tethering_desc':
          'Chia sẻ kết nối Internet từ máy tính sang thiết bị Android của bạn qua cổng USB.',
      'start_reverse_tethering': 'Bắt đầu chia sẻ mạng',
      'stop_reverse_tethering': 'Dừng chia sẻ mạng',
      'gnirehtet_path': 'Đường dẫn tệp tin Gnirehtet',
      'reverse_tethering_active': 'Đang chia sẻ mạng',
      'reverse_tethering_inactive': 'Không chia sẻ mạng',
      'vpn_instruction':
          'Vui lòng mở khóa điện thoại và bấm Đồng ý yêu cầu cấp quyền kết nối VPN sau khi bắt đầu.',
      'gnirehtet_logs': 'Nhật ký kết nối Gnirehtet',
      'about': 'Giới thiệu',
      'about_version': 'Phiên bản',
      'about_desc':
          'Bộ công cụ quản lý thiết bị Android trên Windows với giao diện Bento Liquid Glass, ADB/Scrcpy, thiết bị không dây, chẩn đoán, workspace, cài đặt APK/XAPK hàng loạt thích ứng, bộ nhớ đệm Ảnh & Video mới theo từng thiết bị, Safe Sync v2, sao lưu/khôi phục, bảo vệ file tải xuống, giữ thiết bị đích cho tác vụ hàng loạt và chia sẻ mạng Gnirehtet tự động cài client.',
      'guide_title': 'Hướng dẫn sử dụng',
      'guide_connect':
          '1. Cài đặt Driver & Kết nối: Cài đặt Driver USB cho điện thoại của bạn (tải driver của hãng Xiaomi, Samsung... hoặc Google USB Driver), sau đó bật tính năng "Gỡ lỗi USB" (USB Debugging/ADB) trong Tùy chọn nhà phát triển trên điện thoại trước khi kết nối bằng cáp USB.',
      'guide_mirror':
          '2. Xem màn hình — Bấm "Khởi chạy truyền hình" để xem và điều khiển màn hình thiết bị trên PC.',
      'guide_file':
          '3. Quản lý tệp — Duyệt, tải lên, tải xuống và xóa tệp. Chỉ thay file trên PC khi tải thành công; chọn đích mới nếu tên thư mục đã tồn tại.',
      'guide_sync':
          '4. Safe Sync v2 — Xem trước file sẽ sao chép, cập nhật hoặc xóa trước khi chạy. Mirror Sync yêu cầu nhập DELETE để xác nhận đúng danh sách xóa. Tác vụ đang chạy giữ nguyên thiết bị ban đầu khi bạn đổi lựa chọn.',
      'guide_media':
          '5. Ảnh & Video mới — Dữ liệu bắt đầu tải sau khi phát hiện thiết bị và được lưu theo từng thiết bị khi chuyển đổi; bấm Làm mới để truy vấn lại.',
      'guide_install':
          '6. Cài đặt APK/XAPK — Trên desktop, bố cục hai cột đặt bộ chọn và hàng đợi bên trái, chi tiết và log dễ đọc tự giãn bên phải. Chọn nhiều tệp APK/XAPK, kiểm tra hàng đợi rồi cài tuần tự; gói nén được kiểm tra an toàn trước khi giải nén. Toàn bộ hàng đợi giữ nguyên thiết bị đích ban đầu.',
      'guide_tether':
          '7. Chia sẻ mạng đảo chiều — Chia sẻ mạng Internet từ PC sang thiết bị qua Gnirehtet. Client APK được tự động phát hiện và cài đặt qua ADB nếu máy chưa có.',
      'guide_tools':
          '8. Công cụ nhanh — Gửi văn bản, mô phỏng phím, khởi động lại, chụp ảnh màn hình và nhiều hơn nữa.',
      'guide_settings':
          '9. Năng suất & cài đặt — Cấu hình đường dẫn, lưu profile Scrcpy, kết nối ADB không dây, xem Chẩn đoán và Workspace, dùng Command Palette bằng Ctrl+K, sao lưu/khôi phục cấu hình và kiểm tra GitHub Releases. Ngôn ngữ được ghi nhớ giữa các lần mở; debug.bat bật timestamp chẩn đoán.',
      'about_close': 'Đóng',
      'about_made_by': 'Được tạo với ❤️ bởi JA Team',
      'project_website': 'Website dự án',
      'source_code': 'Mã nguồn',
      'open_link_failed': 'Không thể mở liên kết.',
      'sync_folders_btn': 'Đồng bộ thư mục',
      'sync_folders_title': 'Đồng bộ thư mục PC & Android',
      'pc_folder_label': 'Thư mục PC:',
      'android_folder_label': 'Thư mục Android:',
      'sync_direction_label': 'Chiều đồng bộ:',
      'sync_direction_pc_to_android': 'PC -> Android (Tải lên/Ghi đè)',
      'sync_direction_android_to_pc': 'Android -> PC (Tải về/Ghi đè)',
      'sync_direction_newest': 'Đồng bộ file mới nhất (Bỏ qua trùng lặp)',
      'auto_sync_label': 'Tự động đồng bộ khi kết nối thiết bị',
      'delete_extra_files_label': 'Xóa tệp thừa ở thư mục đích (Mirror Sync)',
      'start_sync_btn': 'Bắt đầu đồng bộ',
      'pause_sync_btn': 'Tạm dừng',
      'resume_sync_btn': 'Tiếp tục',
      'sync_status_idle':
          'Cấu hình đường dẫn và tùy chọn, sau đó nhấn Bắt đầu đồng bộ.',
      'select_pc_folder_hint': 'Chọn thư mục PC...',
      'error_select_pc_folder': 'Vui lòng chọn thư mục PC hợp lệ.',
      'recent_sync_title': 'Cấu hình gần đây',
      'get_current_folder_btn': 'Lấy thư mục đang duyệt',
      'copy_log_btn': 'Sao chép nhật ký',
      'clear_log_btn': 'Xóa nhật ký',
      'sync_history_empty': 'Chưa có lịch sử đồng bộ.',
      'clear_history_btn': 'Xóa lịch sử',
    },
    'zh': {
      'sync_history_summary': '方向：{direction} | 镜像：{mirror}',
      'yes_label': '是',
      'no_label': '否',
      'sync_status_label': '状态：{status}',
      'sync_starting': '正在启动…',
      'sync_scanning': '正在扫描…',
      'sync_comparing': '正在比较…',
      'sync_running': '正在同步…',
      'sync_completed': '已完成',
      'sync_error': '错误',
      'sync_cancelled': '已取消',
      'sync_paused': '已暂停',
      'parent_directory': '返回上级目录',
      'delete_selected_success': '已删除所选项！',
      'delete_some_failed': '部分项目删除失败。',
      'create_directory_failed': '创建目录失败',
      'delete_item_failed': '删除项目失败。',
      'retry_action': '重试',
      'refresh_action': '刷新',
      'rescan_media': '重新扫描媒体',
      'media_scan_hint': '扫描设备媒体索引以查看照片和视频。',
      'split_apks_label': '拆分 APK',
      'xapk_archive': 'XAPK 应用包',
      'standalone_apk': '独立 APK',
      'target_device_ready': '目标设备已就绪',
      'android_device_label': 'Android 设备',
      'sideload_hint': '选择上方的 APK 或 XAPK 文件以开始安装。',
      'copied_package_id': '已复制包名',
      'version_label': '版本',
      'type_label': '类型',
      'terminal_log': '终端日志',
      'log_copied': '日志已复制到剪贴板',
      'installer_waiting': '已就绪。等待开始安装…',
      'copy_package_id': '复制包名',
      'system_app_badge': '系统应用',
      'user_app_badge': '用户应用',
      'frozen_badge': '已冻结',
      'active_badge': '活跃',
      'processing_label': '正在处理…',
      'sync_preview_failed': '无法创建同步预览。',
      'sync_preview_title': '同步预览',
      'files_to_delete': '待删除文件',
      'confirm_delete_hint': '输入 DELETE 确认',
      'browse_pc_folder': '选择电脑文件夹',
      'restore_configuration': '恢复配置',
      'two_way_newest': '双向（最新）',
      'select_pc_directory': '选择电脑目录',
      'delta_sync_title': '双向增量同步',
      'delta_sync_hint': '仅按大小和时间戳传输新增或修改的文件，以加快同步。',
      'dry_run_title': '同步前预检',
      'dry_run_hint': '更改文件前先完整扫描，预览将新增或修改的文件数量。',
      'mirror_mode_title': '镜像模式（删除多余文件）',
      'console_log': '控制台日志',
      'sync_waiting': '等待开始同步…',
      'items_count': '{count} 项',
      'no_files_matching': '没有匹配“{query}”的文件',
      'error_details': '错误：{error}',
      'media_downloaded': '已将 {count} 个文件下载到 {path}',
      'media_partial_download': '复制完成但有警告。请检查文件夹：{path}',
      'media_folder_set': '媒体下载文件夹已设为：{path}',
      'create_target_failed': '无法创建目标目录：{error}',
      'packages_prepared': '已准备 {count} 个包以依次安装。',
      'copied_value': '已复制：{value}',
      'installed_time': '安装时间：{time}',
      'freeze_app_failed': '无法冻结 {app}',
      'unfreeze_app_failed': '无法解冻 {app}',
      'extracting_app': '正在提取 {app}…',
      'extracting_apps': '正在提取 {count} 个应用…',
      'sync_scanned': '已扫描 {pc} 个电脑文件和 {android} 个 Android 文件。',
      'sync_copy_count': '复制/更新 {count} 项',
      'sync_delete_count': '删除 {count} 项',
      'sync_more_files': '…及其他 {count} 个文件',
      'app_title': 'JA ADB 工具',
      'no_device_connected': '未连接设备',
      'select_device': '从侧边栏选择一个安卓设备以开始。',
      'adb_setup_title': '开启 USB 调试',
      'adb_setup_subtitle': '几步即可连接您的安卓手机',
      'adb_image_disclaimer': '图片为通用安卓界面示意，不同品牌的名称可能略有差异。',
      'adb_illustration_phone': '安卓',
      'adb_illustration_debug': 'USB 调试',
      'adb_image_zoom': '点击放大',
      'adb_step_1': '打开手机上的“设置”。',
      'adb_step_2': '打开“关于手机”，连续点击“版本号”七次以开启开发者选项。',
      'adb_step_3': '打开“开发者选项”，开启“USB 调试”。',
      'adb_step_4': '通过 USB 连接手机、解锁手机，并允许 RSA 调试授权提示。',
      'adb_setup_note': '连接时请保持手机解锁，然后刷新设备列表。',
      'adb_refresh_button': '刷新设备',
      'refresh_devices': '刷新设备列表',
      'scrcpy_tab': '屏幕投屏',
      'file_explorer_tab': '文件管理器',
      'latest_media_tab': '最新媒体',
      'installer_tab': '应用安装器',
      'settings_tab': '高级设置',
      'advanced_settings': '高级设置',
      'launch_mirror': '启动投屏',
      'launch_standalone_mirror': '启动独立窗口 (多设备)',
      'stop_mirror': '停止投屏',
      'take_screenshot': '屏幕截图',
      'select_screenshot_folder': '选择截图保存文件夹',
      'select_download_folder': '选择媒体下载文件夹',
      'predefined_label': '预设模板:',
      'select_predefined_hint': '选择一个模板...',
      'scrcpy_options': '投屏选项',
      'scrcpy_profiles': 'Scrcpy 配置',
      'scrcpy_profile_hint': '配置名称',
      'save_profile': '保存配置',
      'delete_profile': '删除配置',
      'profile_saved': 'Scrcpy 配置已保存。',
      'profile_delete_confirm': '删除配置“{name}”？',
      'stay_on_top': '窗口置顶',
      'fullscreen': '全屏显示',
      'no_control': '仅查看 (无控制)',
      'keep_awake': '保持设备唤醒',
      'borderless': '无边框窗口',
      'disable_audio': '禁用音频 (无声音)',
      'mirror_quality_preset': '画质预设',
      'mirror_preset_low': '轻量 / Wi-Fi',
      'mirror_preset_balanced': '均衡',
      'mirror_preset_high': '高清 / USB',
      'mirror_preset_low_desc': '1024px • 30fps • 3Mbps (最低延迟)',
      'mirror_preset_balanced_desc': '1600px • 60fps • 6Mbps (推荐)',
      'mirror_preset_high_desc': '1920px • 60fps • 10Mbps (清晰 USB)',
      'mirror_starting': '正在连接...',
      'mirror_stopping': '正在停止...',
      'mirror_initializing_hint': '正在初始化 Scrcpy 并同步画面...',
      'mirror_error_title': '无法启动屏幕镜像',
      'mirror_open_standalone': '在独立窗口中打开',
      'mirror_diagnostics': '镜像诊断信息',
      'pc_side': '电脑 (PC)',
      'android_side': '安卓设备',
      'download_selected': '下载到电脑',
      'upload_files': '上传到安卓',
      'new_folder': '新建文件夹',
      'delete_selected': '删除项目',
      'loading': '正在加载...',
      'status': '状态',
      'path_to_adb': 'adb.exe 路径',
      'path_to_scrcpy': 'scrcpy.exe 路径',
      'path_settings_title': '工具路径',
      'path_settings_subtitle': '仅在需要修改 ADB、Scrcpy 或 Gnirehtet 时展开',
      'select_apk_xapk': '选择 APK 或 XAPK 文件',
      'drag_drop_apk_xapk': '点击此处选择 APK/XAPK 文件（可多选）',
      'packages_selected': '已选择 {count} 个安装包',
      'selected_packages': '已选安装包（{count}）',
      'remove_package': '移除安装包',
      'install_button': '安装到设备',
      'installing': '正在安装应用...',
      'installation_success': '应用安装成功！',
      'installation_failed': '安装失败: {error}',
      'apk_details': '安装包详情',
      'no_media_found': '设备上未找到照片或视频。',
      'latest_media_title': '筛选最新照片和视频',
      'media_load_success': '已从设备加载 {count} 个媒体项目。',
      'selected_count': '已选择 {count} 个项目',
      'select_latest': '选择最新:',
      'copying_media': '正在将选定的媒体复制到电脑...',
      'copy_media_success': '成功将 {count} 个文件复制到 {dir}',
      'copy_media_failed': '复制失败: {error}',
      'device_info': '设备信息',
      'language': '语言',
      'theme': '主题',
      'confirm_delete': '确认删除',
      'confirm_delete_msg': '您确定要删除 "{name}" 吗？此操作无法撤销。',
      'create_folder': '创建文件夹',
      'folder_name': '文件夹名称',
      'cancel': '取消',
      'confirm': '确认',
      'create': '创建',
      'save_settings': '保存设置',
      'settings_saved': '设置保存成功！',
      'glass_settings_title': 'Glassmorphism',
      'glass_settings_subtitle': '自定义模糊和透明度',
      'glass_preview': 'Glassmorphism 预览',
      'bg_blur_label': '主背景模糊',
      'bg_opacity_label': '主背景透明度',
      'dialog_blur_label': '对话框模糊',
      'dialog_opacity_label': '对话框透明度',
      'reset_defaults': '默认',
      'user_guide': '使用指南',
      'default_search_btn': '自动检测路径',
      'devices_found': '找到 {count} 个设备',
      'no_devices_found': '未找到设备。请确保手机已启用 USB 调试。',
      'wireless_adb': '无线 ADB',
      'wireless_adb_title': '通过 Wi-Fi 连接',
      'wireless_adb_hint': '输入设备 IP 地址和 ADB 端口。',
      'wireless_host': '设备 IP 地址',
      'wireless_port': 'ADB 端口',
      'wireless_connect': '连接',
      'wireless_disconnect': '断开连接',
      'wireless_saved_endpoints': '已保存的连接',
      'wireless_no_endpoints': '没有已保存的无线连接。',
      'wireless_fix_port_card_title': '固定 5555 端口并切换至 Wi-Fi',
      'wireless_fix_port_card_subtitle':
          '持久化设置 5555 端口，重启 adbd 为 TCP/IP 模式并一键无线连接。',
      'wireless_fix_port_target_device': '目标设备:',
      'wireless_fix_port_detected_ip': '检测到的 Wi-Fi IP:',
      'wireless_fix_port_btn': '固定 5555 端口并连接',
      'wireless_fix_port_detecting_ip': '正在检测 IP...',
      'wireless_fix_port_no_usb_hint':
          '连接一次 USB 数据线即可启用并固定 5555 端口，之后可随时断开数据线进行无线连接。',
      'wireless_fix_port_unplug_hint': '连接成功！现在您可以安全拔下 USB 数据线。',
      'wireless_manual_connect_header': '通过 IP / 端口手动连接',
      'wireless_refresh_ip_tooltip': '刷新 Wi-Fi IP',
      'quick_tool_fix_port_title': '固定 5555 端口 (Wi-Fi)',
      'quick_tool_fix_port_subtitle': 'adb tcpip 5555 并自动连接',
      'diagnostics': '诊断',
      'diagnostics_title': '诊断中心',
      'diagnostics_hint': '检查本地工具和设备连接。',
      'diagnostics_run': '运行诊断',
      'diagnostics_copy': '复制报告',
      'diagnostics_no_report': '运行诊断后查看报告。',
      'workspace': '工作区',
      'workspace_title': '设备工作区',
      'workspace_save_current': '保存当前设备',
      'workspace_name': '工作区名称',
      'workspace_empty': '没有已保存的工作区。',
      'workspace_apply': '打开',
      'workspace_delete': '删除',
      'workspace_saved': '工作区已保存。',
      'command_palette': '命令面板',
      'command_palette_hint': '搜索命令…',
      'backup_restore': '备份与恢复',
      'backup_settings': '备份设置',
      'restore_settings': '恢复设置',
      'backup_hint': '导出或恢复路径、界面偏好、同步设置、配置和工作区。',
      'backup_exported': '设置备份已导出。',
      'backup_imported': '设置已恢复。如路径未立即更新，请重启应用。',
      'backup_failed': '无法导出设置备份。',
      'backup_import_failed': '无法恢复此备份文件。',
      'check_updates': '检查更新',
      'update_title': '软件更新',
      'update_checking': '正在检查 GitHub Releases…',
      'update_available': '已有版本 {version}。',
      'update_up_to_date': '当前已是最新版本（{version}）。',
      'update_unavailable': '暂时无法检查 GitHub Releases。',
      'open_release': '打开发布页',
      'retry': '重试',
      'ota_update_title': '局域网 OTA 软件更新',
      'ota_server_path': '服务器路径 (SMB / UNC)',
      'ota_server_path_hint':
          r'\\10.81.141.226\temp\FBT\JA_PROJECT\JA_Update\JA_adb_tool',
      'ota_username': '用户名',
      'ota_password': '密码',
      'ota_check_interval': '检查频率',
      'ota_interval_startup': '启动时',
      'ota_interval_daily': '每天',
      'ota_interval_weekly': '每周',
      'ota_interval_monthly': '每月',
      'ota_interval_off': '关闭自动',
      'ota_test_connection': '测试连接',
      'ota_connection_success': '连接服务器成功！',
      'ota_connection_failed': '无法连接到服务器：{error}',
      'ota_checking': '正在检查局域网服务器更新…',
      'ota_no_update': '当前已是最新版本（{version}）。',
      'ota_update_available': '有可用新版本：{version}',
      'ota_update_now': '立即更新',
      'ota_updating': '正在更新应用…',
      'ota_downloading': '正在下载更新包…',
      'ota_extracting': '正在解压更新包…',
      'ota_restart_ready': '准备就绪！立即重启…',
      'ota_update_failed': '更新失败：{error}',
      'ota_save_config': '保存 OTA 设置',
      'ota_config_saved': '已成功保存 OTA 设置。',
      'ota_browse_folder': '选择服务器文件夹',
      'ota_package_size': '更新包大小：{size}',
      'ota_release_date': '发布日期：{date}',
      'ota_release_notes': '更新说明',
      'ota_latest_version': '最新版本',
      'ota_current_version': '当前版本',
      'ota_tab_title': '局域网 OTA 更新',
      'plugin_manager': '插件管理器',
      'plugin_empty': '未找到插件 manifest。请仅将可信的 JSON manifest 放入应用数据 plugins 文件夹。',
      'current_path': '当前路径: {path}',
      'quick_tools_tab': '快捷功能',
      'settings_shortcuts': '设置快捷方式',
      'launcher_settings': '默认桌面设置',
      'lock_settings': '锁屏与密码',
      'language_settings': '设备语言设置',
      'developer_options': '开发者选项',
      'wifi_settings': 'Wi-Fi 设置',
      'display_settings': '显示设置',
      'accessibility_settings': '无障碍设置',
      'app_settings': '应用管理',
      'about_phone': '关于手机',
      'device_controls': '设备电源控制',
      'reboot_system': '重启系统',
      'reboot_system_sub': '正常重启设备',
      'reboot_bootloader': '重启至 Fastboot',
      'reboot_bootloader_sub': '进入 Fastboot 模式',
      'reboot_recovery': '重启至 Recovery',
      'reboot_recovery_sub': '进入 Recovery 模式',
      'power_off': '关机',
      'power_off_sub': '安全关闭设备',
      'ntp_time_sync_title': 'NTP 时间同步与诊断',
      'ntp_time_sync_subtitle': '内网 NTP 服务器与快速校时',
      'date_settings': '日期和时间设置',
      'ntp_device_clock_title': '系统时钟状态',
      'ntp_device_time': '设备时间',
      'ntp_pc_time': '电脑时间',
      'ntp_drift_label': '时间偏差',
      'ntp_drift_synced': '时间已同步',
      'ntp_sync_to_pc_btn': '一键同步电脑时间 (1-Click)',
      'ntp_sync_to_pc_success': '设备时钟已成功同步至电脑时间！',
      'ntp_sync_to_pc_failed': '同步设备时钟至电脑时间失败。',
      'ntp_server_config_title': 'NTP 服务器配置',
      'ntp_current_server': '当前服务器:',
      'ntp_server_input_hint': 'NTP 服务器地址或 IP (如 10.81.184.80)',
      'ntp_presets_foxconn': '内网 / Foxconn 预设',
      'ntp_presets_public': '公共 NTP 预设',
      'ntp_test_btn': '测试服务器 (UDP 123 & Ping)',
      'ntp_apply_sync_btn': '应用并同步 (auto_time)',
      'ntp_server_test_success': 'NTP 服务器正常响应！延迟: {ms}ms | 层级: {stratum}',
      'ntp_server_test_failed': 'NTP 服务器测试失败: {error}',
      'ntp_apply_success': '已更新 NTP 服务器并触发网络对时！',
      'ntp_apply_failed': '更新设备 NTP 服务器失败。',
      'ntp_subnet_scanner_title': '局域网 NTP 自动发现扫描',
      'ntp_subnet_input_hint': '网段前缀 (如 10.81.184)',
      'ntp_scan_btn': '扫描网段 (/24)',
      'ntp_scanning': '正在扫描 254 个 IP...',
      'ntp_no_servers_found': '在此网段中未发现响应的 NTP 服务器。',
      'ntp_servers_found': '找到 {count} 个活跃的 NTP 服务器:',
      'ntp_use_server_btn': '使用',
      'ntp_diagnostics_title': '时间诊断与日志',
      'ntp_view_diagnostics_btn': '获取诊断日志',
      'hardware_keys': '按键模拟',
      'key_back': '返回键',
      'key_home': '主页键',
      'key_recents': '多任务键',
      'key_power': '电源键',
      'key_volume_up': '音量加',
      'key_volume_down': '音量减',
      'text_input_tool': '文本输入发送器',
      'text_input_placeholder': '输入要发送到设备活动输入框的文本...',
      'send_text': '发送至设备',
      'confirm_reboot': '确认重启',
      'confirm_reboot_msg': '您确定要重启设备吗？',
      'confirm_power_off': '确认关机',
      'confirm_power_off_msg': '您确定要关闭设备吗？',
      'app_freeze_tab': '应用管理器',
      'uninstall_btn': '卸载',
      'force_stop_btn': '强行停止',
      'clear_data_btn': '清除数据',
      'launch_app_btn': '打开应用',
      'extract_apk_btn': '提取 APK / XAPK',
      'batch_extract_apk': '提取选中的 APK/XAPK',
      'extract_apk_success': '成功提取 {app} 到 {file}',
      'extract_apk_failed': '提取 {app} 的 APK/XAPK 失败',
      'batch_extract_success': '成功提取 {count} 个应用',
      'open_folder': '打开文件夹',
      'file_transfer_completed': '文件传输已成功完成！',
      'file_transfer_failed': '文件传输失败或已取消。',
      'uninstall_confirm': '您确定要卸载 {app} 吗？',
      'clear_data_confirm': '您确定要清除 {app} 的数据吗？',
      'search_apps_placeholder': '按名称 or 包名搜索...',
      'freeze_btn': '冻结',
      'unfreeze_btn': '解冻',
      'show_system_apps': '显示系统应用',
      'refresh_list': '刷新列表',
      'sort_apps_tooltip': '应用排序',
      'sort_by_name': '按名称排序',
      'sort_by_newest': '按最新排序',
      'sort_by_oldest': '按最早排序',
      'no_apps_found': '未找到应用。',
      'select_all_apps': '选择当前显示的所有应用',
      'batch_actions': '批量操作',
      'table_name': '名称',
      'table_size': '大小',
      'table_modified': '修改日期',
      'table_actions': '操作',
      'search_files_hint': '过滤文件...',
      'empty_folder': '此文件夹为空',
      'app_inspector': '应用详情',
      'no_app_selected': '从列表中选择一个应用以查看详情并执行操作。',
      'app_summary_total': '应用总数',
      'app_summary_user': '用户应用',
      'app_summary_system': '系统应用',
      'app_summary_frozen': '已冻结应用',
      'action_launch': '启动应用',
      'action_force_stop': '强行停止',
      'action_clear_data': '清除数据',
      'action_uninstall': '卸载应用',
      'action_extract_apk': '提取 APK',
      'action_clone_app': '应用分身',
      'app_cloner_title': '应用分身工作台 (App Cloner Studio)',
      'app_cloner_subtitle': '将应用制作成独立APK安装包或通过系统分身空间极速运行',
      'clone_tab_apk': 'APK 独立分身 (修改包名)',
      'clone_tab_dual_space': '应用分身空间 (双开/多用户)',
      'target_app': '目标应用',
      'new_app_name_label': '分身应用名称',
      'new_package_id_label': '分身应用包名 (Package ID)',
      'install_after_clone': '分身制作完成后立即安装至设备',
      'save_to_pc': '保存分身 APK 安装包至电脑',
      'choose_export_folder': '选择保存目录',
      'start_cloning_btn': '开始应用分身',
      'cloning_in_progress': '正在进行应用分身处理...',
      'cloning_success': '应用分身制作成功！',
      'cloning_failed': '应用分身制作失败',
      'dual_space_guide_title': '分身空间架构 (极速 & 100%安全)',
      'dual_space_guide_desc':
          '基于 Android 原生多用户工作空间机制。1秒极速分身，保留100%官方正版签名，完美兼容高安全性应用（聊天软件、手机银行、大型游戏等）。',
      'device_profiles_title': '当前设备上的用户空间',
      'create_dual_space_btn': '创建全新分身空间',
      'install_to_space_btn': '分身到此空间',
      'launch_in_space_btn': '在此空间中启动',
      'remove_from_space_btn': '从此空间移除',
      'no_dual_space_found': '此设备尚未创建副分身空间。点击下方按钮即可一键创建。',
      'clone_app_action': '应用分身',
      'clone_apk_file': '分身 APK 文件',
      'installer_tips_title': '极速智能安装器',
      'installer_tips_subtitle': '轻松旁加载 Android 应用并享受高级控制',
      'installer_tip_1_title': '批量安装',
      'installer_tip_1_desc': '拖放多个 APK 或 XAPK 文件即可加入安装队列。',
      'installer_tip_2_title': 'ADB 直流安装',
      'installer_tip_2_desc': '通过 USB / Wi-Fi 直接推流安装，无需手动在设备上确认。',
      'installer_tip_3_title': 'Split APK 与 Bundle 支持',
      'installer_tip_3_desc': '完美支持单 APK、分包 APK 集合以及 XAPK 中的 Obb 资源包。',
      'clear_queue': '清空队列',
      'install_to_device': '安装到设备',
      'apk_inspector': '安装包检查器',
      'packages_queued': '已加入 {count} 个安装包',
      'media_filter_all': '全部媒体',
      'media_filter_photos': '照片',
      'media_filter_videos': '视频',
      'scan_media_store': '扫描媒体库',
      'preview_open': '预览并打开',
      'quick_select_presets': '快速选择',
      'sync_pathway_title': '同步路径',
      'sync_pc_target': '电脑文件夹',
      'sync_android_target': '安卓文件夹',
      'sync_overview_title': '同步概览与指引',
      'sync_overview_desc': '通过 ADB 协议进行高性能双向文件同步。',
      'sync_mirror_notice': '镜像模式 (删除多余): 删除目标端存在但源端不存在的文件。',
      'sync_ready_idle': '配置源文件夹和目标文件夹，然后点击开始同步。',
      'batch_freeze': '冻结所选应用',
      'batch_unfreeze': '解冻所选应用',
      'batch_force_stop': '强行停止所选应用',
      'batch_uninstall': '卸载所选应用',
      'batch_uninstall_confirm': '卸载已选择的 {count} 个应用？此操作无法撤销。',
      'batch_result': '完成：{success}；失败：{failed}',
      'reverse_tethering_title': '逆向网络共享 (Gnirehtet)',
      'reverse_tethering_desc': '通过 USB 与安卓设备共享电脑的互联网连接。',
      'start_reverse_tethering': '开启网络共享',
      'stop_reverse_tethering': '停止网络共享',
      'gnirehtet_path': 'Gnirehtet 执行文件路径',
      'reverse_tethering_active': '网络共享已启用',
      'reverse_tethering_inactive': '网络共享已停用',
      'vpn_instruction': '开启后请解锁手机并允许系统 VPN 连接权限申请。',
      'gnirehtet_logs': 'Gnirehtet 连接日志',
      'about': '关于',
      'about_version': '版本',
      'about_desc':
          '一款采用 Bento Liquid Glass 界面的 Windows 安卓设备管理工具，支持 ADB/Scrcpy、无线设备、诊断、工作区、自适应批量 APK/XAPK 安装、按设备预加载最新媒体缓存、Safe Sync v2、备份恢复、安全文件下载、固定设备批量操作以及自动安装客户端的 Gnirehtet 逆向网络共享。',
      'guide_title': '使用指南',
      'guide_connect':
          '1. 驱动与连接：为您的安卓设备安装 USB 驱动程序（例如 Google 或手机厂商官方驱动），然后在手机上开启开发者选项中的“USB 调试” (ADB)，最后通过 USB 连接电脑。',
      'guide_mirror': '2. 屏幕投屏 — 点击"启动投屏"在 PC 上查看并控制设备屏幕。',
      'guide_file':
          '3. 文件管理器 — 浏览、上传、下载和删除文件。下载成功后才替换电脑上的文件；如果目标文件夹已存在，请选择新位置。',
      'guide_sync':
          '4. Safe Sync v2 — 同步前预览复制、更新和删除项；镜像同步必须输入 DELETE 确认准确的删除差异。切换设备不会改变正在运行的同步任务的目标设备。',
      'guide_media': '5. 最新媒体 — 设备发现后会开始加载，并在切换设备时使用对应缓存；需要最新数据时请点击刷新。',
      'guide_install':
          '6. 应用安装器 — 桌面窗口采用两列布局：左侧为选择器和队列，右侧为详情及可扩展的清晰日志。可多选 APK/XAPK 文件，确认队列后按顺序安装；解压前会进行安全校验。整个安装队列保持最初的目标设备。',
      'guide_tether':
          '7. 逆向网络共享 — 通过 Gnirehtet 将电脑网络分享给设备。如果设备未安装客户端，会自动通过 ADB 安装 APK。',
      'guide_tools': '8. 快速工具 — 发送文字、模拟按键、重启、截图等更多功能。',
      'guide_settings':
          '9. 效率与设置 — 配置工具路径、保存 Scrcpy 配置、连接无线 ADB、查看诊断和设备工作区、使用 Ctrl+K 命令面板、备份恢复设置并检查 GitHub Releases。应用语言会保持不变；debug.bat 可输出诊断时间戳。',
      'about_close': '关闭',
      'about_made_by': '由 JA Team ❤️ 打造',
      'project_website': '项目网站',
      'source_code': '源代码',
      'open_link_failed': '无法打开链接。',
      'sync_folders_btn': '文件夹同步',
      'sync_folders_title': '同步 PC 和安卓文件夹',
      'pc_folder_label': 'PC 文件夹:',
      'android_folder_label': '安卓文件夹:',
      'sync_direction_label': '同步方向:',
      'sync_direction_pc_to_android': 'PC -> 安卓 (上传/覆盖)',
      'sync_direction_android_to_pc': '安卓 -> PC (下载/覆盖)',
      'sync_direction_newest': '同步最新文件 (跳过重复项)',
      'auto_sync_label': '连接设备时自动同步',
      'delete_extra_files_label': '删除目标文件夹的多余文件 (镜像同步)',
      'start_sync_btn': '开始同步',
      'pause_sync_btn': '暂停',
      'resume_sync_btn': '继续',
      'sync_status_idle': '配置路径和选项，然后点击开始同步。',
      'select_pc_folder_hint': '选择 PC 文件夹...',
      'error_select_pc_folder': '请选择有效的 PC 文件夹。',
      'recent_sync_title': '最近的配置',
      'get_current_folder_btn': '获取当前目录',
      'copy_log_btn': '复制日志',
      'clear_log_btn': '清除日志',
      'sync_history_empty': '没有最近的同步历史。',
      'clear_history_btn': '清除历史',
    },
  };

  String translate(String key, {Map<String, String>? args}) {
    String value =
        _localizedValues[_locale]?[key] ?? _localizedValues['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }

  String tr(String key, {Map<String, String>? args}) =>
      translate(key, args: args);
}

extension LocalizationExtension on BuildContext {
  String tr(String key, {Map<String, String>? args}) {
    return Provider.of<LanguageProvider>(this).translate(key, args: args);
  }
}
